version: '3.3'
services:
  api:
    build: ./api
    volumes:
    - ./api/:/src:cached
    command: sh -c "npm install && node index.js"
    ports:
    - 8080:8080

  ui:
    build: ./ui
    #image: ecomputer/angular4
    volumes:
    - ./ui/quiz:/src
    command: sh -c "npm install && ng serve --host 0.0.0.0 --port 4200"
    #command: sh -c "while true; do sleep 1000; done; npm install;"
    ports:
    - 4200:4200


  mongo:
    image: 'mongo:3.4.1'
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db

volumes:
  mongo:
