version: '3.3'
services:
  api:
    build: ./api
    volumes:
    - ./api/:/src:cached
    command: sh -c "npm install && node index.js"
    ports:
    - 8080:8080

  ui:
    build: ./ui
    volumes:
    - ./ui/:/src:cached
    command: sh -c "while true; do sleep 1000; done; npm install;"
    ports:
    - 8081:8081
